name: socialindiepro_app
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_speed_dial: ^1.2.5
  cloud_firestore:
  firebase_core: ^0.5.0
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  get: ^3.4.6
  # Rotas, Injeção de Dependencia
  flutter_modular: ^2.0.1
  # Firebase
  firebase_auth: ^0.18.1+1
  google_sign_in: ^4.5.4
  # Gerenciamento de Estado
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  # Pacote de icons https://feathericons.com/
  flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0+2
  build_runner:
  effective_dart: ^1.2.4



flutter:
  uses-material-design: true

  assets:
    - lang/
    - assets/images/

  fonts:
      - family: Google
#        fonts:
#          - asset: assets/fonts/ProductSans-Regular.ttf
#          - asset: assets/fonts/ProductSans-Bold.ttf
#            weight: 700 
